local theme = require('base46').get_theme_tb('base_16')

return {
  ['@attribute'] = { fg = theme.base0A },
  ['@character'] = { fg = theme.base08 },
  ['@annotation'] = { link = 'PreProc' },
  ['@boolean'] = { fg = theme.base09 },
  ['@number'] = { fg = theme.base09 },
  ['@float'] = { link = '@number' },
  ['@comment'] = { fg = theme.base02 },
  ['@type.qualifier'] = { fg = theme.base0B },
  ['@constructor'] = { fg = theme.base0C },
  ['@constant'] = { fg = theme.base08 },
  ['@constant.builtin'] = { link = '@constant' },
  ['@constant.macro'] = { fg = theme.base08 },
  ['@error'] = { fg = theme.base09 },
  ['@exception'] = { link = '@error' },
  ['@function'] = { fg = theme.base0D },
  ['@function.builtin'] = { link = '@function' },
  ['@function.call'] = { link = '@function' },
  ['@function.macro'] = { fg = theme.base08 },
  ['@keyword'] = { fg = theme.base0E },
  ['@keyword.function'] = { link = '@keyword' },
  ['@keyword.return'] = { link = '@keyword' },
  ['@keyword.export'] = { link = '@keyword' },
  ['@keyword.operator'] = { fg = theme.base0E },
  ['@include'] = { link = '@keyword' },
  ['@conditional'] = { link = '@keyword' },
  ['@repeat'] = { link = '@keyword' },
  ['@method'] = { fg = theme.base0D },
  ['@method.call'] = { link = '@method' },
  ['@namespace'] = { fg = theme.base08 },
  ['@none'] = { link = '@boolean' },
  ['@parameter'] = { fg = theme.base08 },
  ['@reference'] = { fg = theme.base05 },
  ['@delimiter'] = { fg = theme.base0F },
  ['@punctuation.bracket'] = { fg = theme.base0F },
  ['@punctuation.delimiter'] = { fg = theme.base0F },
  ['@punctuation.special'] = { fg = theme.base08 },
  ['@string'] = { fg = theme.base0B },
  ['@storageclass'] = { fg = theme.base0A },
  ['@string.regex'] = { fg = theme.base0C },
  ['@string.escape'] = { fg = theme.base0C },
  ['@symbol'] = { fg = theme.base0B },
  ['@tag'] = { fg = theme.base0A },
  ['@tag.attribute'] = { link = '@property' },
  ['@tag.delimiter'] = { fg = theme.base0F },
  ['@text'] = { fg = theme.base05 },
  ['@text.math'] = { fg = theme.base0D },
  ['@text.strong'] = { bold = true },
  ['@text.emphasis'] = { fg = theme.base09 },
  ['@text.strike'] = { fg = theme.base00, strikethrough = true },
  ['@text.literal'] = { fg = theme.base09 },
  ['@text.uri'] = { fg = theme.base09, underline = true },
  ['@type'] = { fg = theme.base0A, sp = 'none' },
  ['@type.builtin'] = { link = '@type' },
  ['@variable'] = { fg = theme.base05 },
  ['@variable.builtin'] = { fg = theme.base09 },
  ['@definition'] = { sp = theme.base04, underline = true },
  TSDefinitionUsage = { sp = theme.base04, underline = true },
  ['@scope'] = { bold = true },
  ['@field'] = { fg = theme.base08 },
  ['@field.key'] = { fg = theme.base0D },
  ['@property'] = { fg = theme.base08 },
}
